# Generated by Django 5.2.14 on 2026-07-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ensure_contactmessage_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number_ng', models.CharField(blank=True, default='', help_text='International format, e.g. +2347045036178. Used when the store currency is NGN.', max_length=20, verbose_name='WhatsApp number (Nigeria)')),
                ('whatsapp_number_gh', models.CharField(blank=True, default='', help_text='International format, e.g. +233201234567. Used when the store currency is GHS.', max_length=20, verbose_name='WhatsApp number (Ghana)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store settings',
                'verbose_name_plural': 'Store settings',
            },
        ),
    ]
