# Generated by Django 5.2.14 on 2026-07-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_ghs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
